name: Playwright Tests

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Generate .env file
        env:
          BRIGHTHRLITE_URL: ${{ vars.BRIGHTHRLITE_URL }}
          BRIGHTHRLITE_EMAIL: ${{ secrets.BRIGHTHRLITE_EMAIL }}
          BRIGHTHRLITE_PASSWORD: ${{ secrets.BRIGHTHRLITE_PASSWORD }}
        run: envsubst < ./setup/env > .env

      - name: Run Playwright tests
        run: npx playwright test

